- app/frontend/stylesheets/object/project/_DetailHeader.sass
一変異ビューのDetailHeaderのCSSが崩れているのを修正いたしました。（sassのインデントがずれていたようです）![スクリーンショット 2020-10-28 14 43 21](https://user-images.githubusercontent.com/70997801/97397190-08b0ec00-192c-11eb-8e69-c8ef61992862.png)
> adjusted appearance of DetailHeader

- app/frontend/assets/tooltips.json
Updated tooltips comments in https://github.com/togovar/togovar/blob/staging/app/frontend/assets/tooltips.json 
See https://github.com/biosciencedbc/togovar/issues/85#issuecomment-1120525637
> tooltips comments updated

- app/frontend/javascripts/classes/ConditionValueEditorFrequencyCount.js
- app/frontend/javascripts/classes/PanelViewFilterAlternativeAlleleFrequency.js
- app/frontend/javascripts/components/RangeSliderView.js
- Range slider では 0.05 刻みにしか表示されないというバグを修正し、0.01 刻みに変更いたしました。
> Range slider bugfix

- app/frontend/views/doc/en/about.pug
- app/frontend/views/doc/ja/about.pug
- app/frontend/views/doc/ja/help.pug
docの修正です。４月に変更になったNBDCの名称をAboutに反映できていなかったのでhotfixを出しました。急ぎませんので適当なタイミングでマージしていただけると助かります。
> update NBDC name and fix typo in help

- app/frontend/javascripts/components/ConditionDiseaseSearch/ConditionDiseaseSearchColumn.js
> fix ontology Column

- app/frontend/stylesheets/object/component/_advanced-search-condition-item-view.sass
- app/frontend/stylesheets/object/project/_SimpleSearchView.sass
> fix webpack warning

- app/frontend/javascripts/classes/StoreManagerMixin.js
error modalに関して修正を行いました。
ご確認をお願いします。
> fix error-modal

- app/frontend/views/doc/en/about.pug
- app/frontend/views/doc/en/datasets_grch37.pug
- app/frontend/views/doc/en/datasets_grch38.pug
- app/frontend/views/doc/en/terms.pug
- app/frontend/views/doc/ja/about.pug
- app/frontend/views/doc/ja/datasets_grch37.pug
- app/frontend/views/doc/ja/datasets_grch38.pug
- app/frontend/views/doc/ja/help.pug
- app/frontend/views/doc/ja/terms.pug
Updated document pages specified in  https://github.com/togovar/meeting/issues/140
> Hotfix document pages

- app/frontend/javascripts/components/ConditionDiseaseSearch/ConditionDiseaseSearch.js
- app/frontend/javascripts/components/ConditionDiseaseSearch/ConditionDiseaseSearchOntologyView.js
疾患検索のDAGに最初から　root node を表示させる
> show first node on load

- app/frontend/views/doc/en/about.pug
- app/frontend/views/doc/ja/about.pug
Please merge the update of the project organization in the About page.
> update statement of project organization in About page

- .babelrc
- package-lock.json
- package.json
@dsatoh
Litでdecoratorを使用したいので、babelに追記しました。
ご確認をお願いします。
参考記事：[https://lit.dev/docs/components/decorators/](https://lit.dev/docs/components/decorators/)
> add @babel/plugin-proposal-decorators for lit

- app/frontend/views/doc/en/help.pug
- app/frontend/views/doc/ja/help.pug
以下の２点についてヘルプを修正したので、developにマージしてください。
1. SIFT、Polyphen-2、AlphaMissenseの説明の変更
2. liftoverツールをtransannoに変更
> Update help page

- app/frontend/javascripts/components/Common/SearchField/SearchFieldWithSuggestions.js
@dsatoh simple serchの検索においてbugが発生していたので、returnを削除しました。
> remove return

- app/frontend/views/doc/en/datasets/analysis_grch38.pug
- app/frontend/views/doc/en/help.pug
- app/frontend/views/doc/en/history.pug
- app/frontend/views/doc/ja/datasets/analysis_grch38.pug
- app/frontend/views/doc/ja/help.pug
- app/frontend/views/doc/ja/history.pug
Documents to be updated include help, history, and analysis pages.
> Update documents for release of AlphaMissense and fixing typo

- app/frontend/config/stanza.yaml
tableのstanzaにデータが無いときにNo dataと記述するよう変更しました。
ご確認をお願いします。
> add nodata to stanza

- app/frontend/config/stanza.yaml
metastanzaのParameterが変更となりましたので、再度ご確認をお願いします。
> fix stanza param of No Data

- app/frontend/config/stanza.yaml
- app/frontend/views/disease/index.pug
- app/frontend/views/gene/index.pug
- app/frontend/views/variant/index.pug
stanzaのlinkのidを変更しました。
stanzaのnodataのparamsを再度変更しました。
ご確認をお願いします。
> fix stanza link

- app/frontend/assets/togovar.jsonld
- app/frontend/config/webpack.config.common.js
- app/frontend/views/doc/en/about.pug
- app/frontend/views/doc/en/datasets/gem_j_wga_grch37.pug
- app/frontend/views/doc/en/datasets/gem_j_wga_grch38.pug
- app/frontend/views/doc/en/datasets/jga_ngs_grch37.pug
- app/frontend/views/doc/en/datasets/jga_ngs_grch38.pug
- app/frontend/views/doc/en/datasets/jga_snp_grch37.pug
- app/frontend/views/doc/en/datasets/jga_snp_grch38.pug
- app/frontend/views/doc/en/datasets/ncbn.pug
- app/frontend/views/doc/en/datasets/ncbn_grch38.pug
- app/frontend/views/doc/en/datasets_grch37.pug
- app/frontend/views/doc/en/datasets_grch38.pug
- app/frontend/views/doc/en/history.pug
- app/frontend/views/doc/ja/about.pug
- app/frontend/views/doc/ja/datasets/gem_j_wga_grch37.pug
- app/frontend/views/doc/ja/datasets/gem_j_wga_grch38.pug
- app/frontend/views/doc/ja/datasets/jga_ngs_grch37.pug
- app/frontend/views/doc/ja/datasets/jga_ngs_grch38.pug
- app/frontend/views/doc/ja/datasets/jga_snp_grch37.pug
- app/frontend/views/doc/ja/datasets/jga_snp_grch38.pug
- app/frontend/views/doc/ja/datasets/ncbn.pug
- app/frontend/views/doc/ja/datasets/ncbn_grch38.pug
- app/frontend/views/doc/ja/datasets_grch37.pug
- app/frontend/views/doc/ja/datasets_grch38.pug
- app/frontend/views/doc/ja/history.pug
- app/frontend/views/includes/_dataset_schema.pug
2024.1に公開に必要なドキュメントページを追記、更新しました。developからブランチしたのでdevelopにPRしますが、適切なブランチにマージしてもらえると助かります。
> update and add documents for 2024.1 release

- app/frontend/javascripts/components/LogarithmizedBlockGraphFrequencyView.js
frequencyの変数を変更し、トップページが表示されるよう変更しました。
> fix frequency variable name

- app/frontend/config/stanza.yaml
- app/frontend/javascripts/classes/PanelViewPreviewAlternativeAlleleFrequencies.js
- app/frontend/javascripts/classes/PanelViewPreviewClinicalSignificance.js
- app/frontend/javascripts/classes/ResultsRowView.js
stanzaのparamsの変更、データ構造変更に伴う変数の変更を行いました。
よろしくお願いします。
> fix stanza and variable name

- app/frontend/views/doc/en/datasets/gem_j_wga_grch37.pug
- app/frontend/views/doc/en/datasets/gem_j_wga_grch38.pug
- app/frontend/views/doc/en/datasets/jga_ngs_grch37.pug
- app/frontend/views/doc/en/datasets/jga_ngs_grch38.pug
- app/frontend/views/doc/en/datasets/jga_snp_grch37.pug
- app/frontend/views/doc/en/datasets/jga_snp_grch38.pug
- app/frontend/views/doc/en/datasets/ncbn_grch38.pug
- app/frontend/views/doc/en/downloads.pug
- app/frontend/views/doc/en/history.pug
- app/frontend/views/doc/ja/datasets/gem_j_wga_grch37.pug
- app/frontend/views/doc/ja/datasets/gem_j_wga_grch38.pug
- app/frontend/views/doc/ja/datasets/jga_snp_grch37.pug
- app/frontend/views/doc/ja/datasets/jga_snp_grch38.pug
- app/frontend/views/doc/ja/datasets/ncbn_grch38.pug
- app/frontend/views/doc/ja/datasets_grch38.pug
- app/frontend/views/doc/ja/downloads.pug
- app/frontend/views/doc/ja/history.pug
> Fix documents for 2024.1 release

- app/frontend/stylesheets/object/component/_common-document.sass
- app/frontend/views/doc/en/datasets/jga_snp_grch37.pug
- app/frontend/views/doc/en/datasets/jga_snp_grch38.pug
- app/frontend/views/doc/ja/datasets/jga_snp_grch37.pug
- app/frontend/views/doc/ja/datasets/jga_snp_grch38.pug
jumpする位置を変更するためにstyleを追加しました。ご確認をお願いします。
> add scroll-margin-top

- app/frontend/views/doc/en/datasets/gem_j_wga_grch37.pug
- app/frontend/views/doc/en/datasets/gem_j_wga_grch38.pug
- app/frontend/views/doc/en/datasets/jga_snp_grch37.pug
- app/frontend/views/doc/en/datasets/jga_snp_grch38.pug
- app/frontend/views/doc/en/datasets/ncbn_grch38.pug
- app/frontend/views/doc/en/datasets_grch38.pug
- app/frontend/views/doc/en/history.pug
- app/frontend/views/doc/ja/datasets/gem_j_wga_grch37.pug
- app/frontend/views/doc/ja/datasets/gem_j_wga_grch38.pug
- app/frontend/views/doc/ja/datasets/jga_snp_grch37.pug
- app/frontend/views/doc/ja/datasets/jga_snp_grch38.pug
- app/frontend/views/doc/ja/datasets/ncbn_grch38.pug
- app/frontend/views/doc/ja/datasets_grch38.pug
- app/frontend/views/doc/ja/history.pug
> update documents for 2024.1 release

- app/frontend/javascripts/classes/ConditionValueEditorColumnsDataset.ts
- app/frontend/javascripts/classes/StoreManager.js
- app/frontend/stylesheets/object/component/_columns-editor-view.sass
- app/frontend/stylesheets/object/project/_Messages.sass
Datasetを表示した際のloginのstyleを変更しました。
ご確認をお願いします。
> fix style of login

- package-lock.json
- package.json
build errorが出ているため、lodashのtypeに関する変更を行いました。
> add @types/lodash

- app/frontend/src/api/fetchData.ts
- app/frontend/src/classes/ConditionValueEditorColumnsDataset.ts
- app/frontend/src/store/StoreManager.ts
loginstatusがスクロールする度に表示されるので修正しました。
> fix login status

- app/frontend/stylesheets/object/component/_stanza-view.sass
stanza #gene-protein-browserに関するstyleを変更しました。
ご確認をお願いします。
> fix stanza of gene-protein-browser

- app/frontend/stylesheets/object/component/_stanza-view.sass
- app/frontend/views/disease/index.pug
- app/frontend/views/gene/index.pug
- app/frontend/views/layouts/application.pug
- app/frontend/views/variant/index.pug
以下の修正を行いました。
- min-heightの設定を見直しました。
- ジャンプするタイミングをsetTimeoutで調整しました。
> refactor stanza display

- app/frontend/src/components/Common/SearchField/SearchField.js
- app/frontend/src/components/Common/SearchField/SearchFieldWithSuggestions.js
- app/frontend/src/components/Common/SearchField/SimpleSearchView.js
- app/frontend/src/store/searchManager.ts
Simple searchで検索欄が空欄の際に条件を追加するとurlのtermが消えるように変更しました。
ご確認をお願いします。
> add logic to update the URL term

- app/frontend/config/stanza.yaml
- app/frontend/views/doc/en/history.pug
- app/frontend/views/doc/ja/history.pug
> History 2025.1
